title:              Bransgore Vets
description:        Small Animal Vets in Bransgore

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://psaikido.github.io/bransgore-vets"

# Site logo, dark and light depending on page hero text setting dark/light
logo_image:
  light: logo-bransgorevets.jpg

# Author settings, displayed on about page
author:
    name:           Hugh Carroll
    email:          hughie@carrollonline.co.uk
    website:        https://hugle.co.uk

# Social share buttons
# twitter_username:   somename
# github_username:    somename

# Default footer image settings
footer:
   copyright:      Bransgrove Vets 2007 - 2022


google_analytics: 'UA-21819795-4'

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Path to post content assets directory i.e post images, pdfs etc
post_assets:        /assets/posts/
img_assets:         /assets/img/

defaults:
  - scope:
      path: "newsletters"
    values:
      pdf: true

# Build settings
markdown:           kramdown
highlighter:        rouge

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - tmp/

sass:
  style:            compressed

collections:
  faqs:
    output: false
